/* Simulation code for oc_latch generated by the OpenModelica Compiler OpenModelica v1.19.0-dev-782-g7efd350be1 (64-bit). */
#if !defined(oc_latch__MODEL_H)
#define oc_latch__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "oc_latch_functions.h"

#define Modelica_Blocks_Tables_Internal_getNextTimeEvent_index 0
#define Modelica_Blocks_Tables_Internal_getTimeTableTmax_index 1
#define Modelica_Blocks_Tables_Internal_getTimeTableTmin_index 2
#define Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer_index 3
#define Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index 4
#define Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_index 5

extern void oc_latch_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void oc_latch_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void oc_latch_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int oc_latch_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int oc_latch_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int oc_latch_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int oc_latch_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int oc_latch_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int oc_latch_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int oc_latch_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int oc_latch_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int oc_latch_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int oc_latch_checkForAsserts(DATA *data, threadData_t *threadData);
extern int oc_latch_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int oc_latch_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int oc_latch_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* oc_latch_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* oc_latch_relationDescription(int i);
extern void oc_latch_function_initSample(DATA *data, threadData_t *threadData);
extern int oc_latch_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int oc_latch_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int oc_latch_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int oc_latch_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int oc_latch_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int oc_latch_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int oc_latch_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int oc_latch_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int oc_latch_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int oc_latch_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int oc_latch_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int oc_latch_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* oc_latch_linear_model_frame(void);
extern const char* oc_latch_linear_model_datarecovery_frame(void);
extern int oc_latch_mayer(DATA* data, modelica_real** res, short *);
extern int oc_latch_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int oc_latch_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int oc_latch_setInputData(DATA *data, const modelica_boolean file);
extern int oc_latch_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void oc_latch_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void oc_latch_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int oc_latch_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void oc_latch_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void oc_latch_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int oc_latch_inputNames(DATA* data, char ** names);
extern int oc_latch_dataReconciliationInputNames(DATA* data, char ** names);
extern int oc_latch_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int oc_latch_functionLocalKnownVars(DATA*, threadData_t*);
extern int oc_latch_symbolicInlineSystem(DATA*, threadData_t*);

#include "oc_latch_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(oc_latch__MODEL_H) */


