/* Additional record code for oc_latch generated by the OpenModelica Compiler OpenModelica v1.19.0-dev-782-g7efd350be1 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "oc_latch_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

