# DO NOT EDIT THIS FILE!
#
# Python module _GlobalIDL__POA generated by omniidl

import omniORB
omniORB.updateModule("_GlobalIDL__POA")

# ** 1. Stub files contributing to this module
import stubs.OmcClient_idl

# ** 2. Sub-modules

# ** 3. End
