# Python stubs generated by omniidl from OmcClient.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "_GlobalIDL"
#
__name__ = "_GlobalIDL"
_0__GlobalIDL = omniORB.openModule("_GlobalIDL", r"OmcClient.idl")
_0__GlobalIDL__POA = omniORB.openModule("_GlobalIDL__POA", r"OmcClient.idl")


# interface OmcCommunication
_0__GlobalIDL._d_OmcCommunication = (omniORB.tcInternal.tv_objref, "IDL:OmcCommunication:1.0", "OmcCommunication")
omniORB.typeMapping["IDL:OmcCommunication:1.0"] = _0__GlobalIDL._d_OmcCommunication
_0__GlobalIDL.OmcCommunication = omniORB.newEmptyClass()
class OmcCommunication :
    _NP_RepositoryId = _0__GlobalIDL._d_OmcCommunication[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0__GlobalIDL.OmcCommunication = OmcCommunication
_0__GlobalIDL._tc_OmcCommunication = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_OmcCommunication)
omniORB.registerType(OmcCommunication._NP_RepositoryId, _0__GlobalIDL._d_OmcCommunication, _0__GlobalIDL._tc_OmcCommunication)

# OmcCommunication operations and attributes
OmcCommunication._d_sendExpression = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)

# OmcCommunication object reference
class _objref_OmcCommunication (CORBA.Object):
    _NP_RepositoryId = OmcCommunication._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def sendExpression(self, *args):
        return _omnipy.invoke(self, "sendExpression", _0__GlobalIDL.OmcCommunication._d_sendExpression, args)

    __methods__ = ["sendExpression"] + CORBA.Object.__methods__

omniORB.registerObjref(OmcCommunication._NP_RepositoryId, _objref_OmcCommunication)
_0__GlobalIDL._objref_OmcCommunication = _objref_OmcCommunication
del OmcCommunication, _objref_OmcCommunication

# OmcCommunication skeleton
__name__ = "_GlobalIDL__POA"
class OmcCommunication (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.OmcCommunication._NP_RepositoryId


    _omni_op_d = {"sendExpression": _0__GlobalIDL.OmcCommunication._d_sendExpression}

OmcCommunication._omni_skeleton = OmcCommunication
_0__GlobalIDL__POA.OmcCommunication = OmcCommunication
omniORB.registerSkeleton(OmcCommunication._NP_RepositoryId, OmcCommunication)
del OmcCommunication
__name__ = "_GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "stubs.OmcClient_idl"

_exported_modules = ( "_GlobalIDL", )

# The end.
