top_builddir= ../
builddir_bin=$(top_builddir)/build/bin
builddir_lib=$(top_builddir)/build/lib
builddir_inc=$(top_builddir)/build/include
builddir_doc=$(top_builddir)/build/doc
builddir_share=$(top_builddir)/build/share

IDLFILE=$(top_builddir)/Compiler/runtime/omc_communication.idl
